//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiderManager.Database_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public long ID { get; set; }
        public long AnimalID { get; set; }
        public long Category { get; set; }
        public string Amount { get; set; }
        public string Note { get; set; }
        public string Date { get; set; }
    
        public virtual Animals Animals { get; set; }
    }
}
